### PR TITLE
Updated push library in pong-1

### PR DESCRIPTION
**Pull request by vidu120**
The old push library was not able to run through the latest version of love2D , so i updated the push library from the source..
The library started working after i updated it.. 
You can see if further edit is needed..

### CODE REVIEW

**Comment by ask4amit** [comment]
👍

**Comment by ask4amit** [comment]
👎  This PR is not complete. It is giving just a white screen for pong-2 onwards with Love@11.3 on Mac

Probably needs more changes such as in https://github.com/games50/pong/pull/34/files

**Comment by vidu120** [comment]
> 👎 This PR is not complete. It is giving just a white screen for pong-2 onwards with Love@11.3 on Mac
> 
> Probably needs more changes such as in https://github.com/games50/pong/pull/34/files

**Comment by vidu120** [comment]
The bug was in love.draw function in the main file ,you can look into it and try running it now..
I think it will work now..

**Pull request closed without merging**
